version: '3.3'
services:

  npk-mysql:
    restart: always
    image: mysql:5.5
    container_name: npk-mysql
    volumes:
      - ./config:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=npk.of.by
      - MYSQL_USER=npk
      - MYSQL_PASSWORD=pa55word
      - MYSQL_ROOT_PASSWORD=pa55word

  npk-joomla:
    restart: always
    image: mantiby/apache-php-5-2:latest
    container_name: npk-joomla
    ports:
      - 8890:80
    links:
      - npk-mysql
    volumes:
      - ./app:/usr/local/apache2/htdocs
    command:
      - /bin/run-apache
