// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Стили --',
theme_code_desc : 'Править HTML код',
theme_code_title : 'HTML Source Editor',
theme_code_wordwrap : 'Перенос слов',
theme_sub_desc : 'Нижний индекс',
theme_sup_desc : 'Верхний индекс',
theme_hr_desc : 'Горизонтальная линия',
theme_removeformat_desc : 'Очистить форматирование',
theme_custom1_desc : 'пользовательское описание здесь',
insert_image_border : 'Граница',
insert_image_dimensions : 'Размеры',
insert_image_vspace : 'Вертикальное пространство',
insert_image_hspace : 'Горизонтальное пространство',
insert_image_align : 'Выравнивание',
insert_image_align_default : '-- Не установлено --',
insert_image_align_baseline : 'Базовая линия',
insert_image_align_top : 'Верх',
insert_image_align_middle : 'Середина',
insert_image_align_bottom : 'Низ',
insert_image_align_texttop : 'Верх текста',
insert_image_align_absmiddle : 'Абсолютная середина',
insert_image_align_absbottom : 'AАбсолютный низ',
insert_image_align_left : 'Лево',
insert_image_align_right : 'Право',
theme_font_size : '-- Размер шрифта --',
theme_fontdefault : '-- Гарнитура шрифта --',
theme_block : '-- Формат --',
theme_paragraph : 'Параграф',
theme_div : 'Div',
theme_address : 'Адрес',
theme_pre : 'Преформатировано',
theme_h1 : 'Заголовок 1',
theme_h2 : 'Заголовок 2',
theme_h3 : 'Заголовок 3',
theme_h4 : 'Заголовок 4',
theme_h5 : 'Заголовок 5',
theme_h6 : 'Заголовок 6',
theme_colorpicker_title : 'Выбор цвета',
theme_colorpicker_apply : 'Применить',
theme_forecolor_desc : 'Выбор цвета текста',
theme_backcolor_desc : 'Выбор цвета фона',
theme_charmap_title : 'Выбор произвольного знака',
theme_charmap_desc : 'Вставить произвольный знак',
theme_visualaid_desc : 'Включить/отключить невидимые элементы',
insert_anchor_title : 'Вставить/править закладку',
insert_anchor_name : 'Имя закладки',
theme_anchor_desc : 'Вставить/править закладку',
theme_insert_link_titlefield : 'Заголовок',
theme_clipboard_msg : 'Копировать/Вырезать/Вставить недоступно в Mozilla и Firefox.\nПоказать больше информации по этому вопросу?',
theme_path : 'Путь',
cut_desc : 'Вырезать',
copy_desc : 'Копировать',
paste_desc : 'Вставить',
link_list : 'Список ссылок',
image_list : 'Список картинок',
browse : 'Просмотр',
image_props_desc : 'Свойства картинки',
newdocument_desc : 'Новый документ',
class_name : 'Класс',
newdocument : 'Вы уверены, что хотите очистить содержимое?',
about_title : 'О редакторе TinyMCE',
about : 'О...',
license : 'Лицензия',
plugins : 'Плагины',
plugin : 'Плагин',
author : 'Автор',
version : 'Версия',
loaded_plugins : 'Загруженные плагины',
help : 'Справка',
not_set : '-- Не установлено --',
close : 'Закрыть',
toolbar_focus : 'Горячие коавиши - Кнопки инструментов - Alt+Q, В окно редактора - Alt-Z, К элементам - Alt-X'
});
