mysql:
  image: mysql:5.5
  ports:
    - "3336:3306"
  volumes:
    - ./db:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_DATABASE=npk.of.by
    - MYSQL_USER=npk
    - MYSQL_PASSWORD=pa55word
    - MYSQL_ROOT_PASSWORD=pa55word

joomla:
  image: mantiby/apache-php-5-2
  ports:
    - "8088:80"
  links:
    - mysql
  volumes:
    - ../app:/usr/local/apache2/htdocs
