// UK lang variables

tinyMCE.addToLang('',{
bold_desc : 'Жирный (Ctrl+B)',
italic_desc : 'Курсив (Ctrl+I)',
underline_desc : 'Подчеркнутый (Ctrl+U)',
striketrough_desc : 'Перечеркнутый',
justifyleft_desc : 'Выравнивание влево',
justifycenter_desc : 'Выравнивание по центру',
justifyright_desc : 'Выравнивание вправо',
justifyfull_desc : 'Выравнивание по обоим краям',
bullist_desc : 'Маркированный список',
numlist_desc : 'Нумерованный список',
outdent_desc : 'Уменьшить отступ',
indent_desc : 'Увеличить отступ',
undo_desc : 'Отмена (Ctrl+Z)',
redo_desc : 'Повтор (Ctrl+Y)',
link_desc : 'Вставить/править ссылку',
unlink_desc : 'Удалить ссылку',
image_desc : 'Вставить/править картинки',
cleanup_desc : 'Очистка кода',
focus_alert : 'Перед использованием этой команды редактор должен быть в фокусе.',
edit_confirm : 'Вы хотите использовать режим WYSIWYG для этого участка текста?',
insert_link_title : 'Вставить/править текст ссылки',
insert : 'Вставить',
update : 'Обновить',
cancel : 'Отмена',
insert_link_url : 'URL-ссылка',
insert_link_target : 'Назначение',
insert_link_target_same : 'Открыть ссылку в этом же окне',
insert_link_target_blank : 'Открыть ссылку в новом окне',
insert_image_title : 'Вставить/править заголовок картинки',
insert_image_src : 'URL источника картинки',
insert_image_alt : 'Описание картинки',
help_desc : 'Справка',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Копировать/Вставить/Вырезать недоступно в Mozilla и Firefox.\nВы хотите получить больше информации об этом?',
popup_blocked : 'Извините, но блокировщик всплывающих окон отрицательно влияет на функциональность редактора. Вам требуется отключить блокировщик для нормального функционирования редактора.'
});
