// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Общие',
popup_tab : 'ПОП-АП',
events_tab : 'События',
advanced_tab : 'Расширенные',
general_props : 'Общие свойства',
popup_props : 'Свойства ПОП-АП',
event_props : 'События',
advanced_props : 'Расширенные свойства',
popup_opts : 'Опции',
anchor_names : 'Якоря',
target_same : 'Открыть в этом окне/фрейме',
target_parent : 'Открыть в родительском окне/фрейме',
target_top : 'Открыть в верхнем фрейме (замещает все фреймы)',
target_blank : 'Открыть в новом окне',
popup : 'JavaScript ПОП-АП',
popup_url : 'ПОП-АП URL',
popup_name : 'Имя окна',
popup_return : 'Insert \'return false\'',
popup_scrollbars : 'Показать полосы прокрутки',
popup_statusbar : 'Показать полосу статуса',
popup_toolbar : 'Показать полосу инструментов',
popup_menubar : 'Показать меню',
popup_location : 'Показать полосу адреса',
popup_resizable : 'Окно может менять размеры',
popup_dependent : 'Зависимо (Mozilla/Firefox only)',
popup_size : 'Размер',
popup_position : 'Позиция (X/Y)',
id : 'Id',
style: 'Стиль',
classes : 'Классы',
target_name : 'Имя назначеия',
langdir : 'Направление письма',
target_langcode : 'Код языка - назначение',
langcode : 'Код языка',
encoding : 'Назначение - кодировка',
mime : 'Назначение MIME тип',
rel : 'Относительно страницы к адресату',
rev : 'Относительно адресата к странице',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Слева направо',
rtl : 'Справа налево'
});
