// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Общие',
advanced_tab : 'Расширенные',
general_props : 'Общие свойства',
advanced_props : 'Расширенные свойства',
desc : 'Вставить новую таблицу',
row_before_desc : 'Вставить строку до',
row_after_desc : 'Вставить строку после',
delete_row_desc : 'Удалить строку',
col_before_desc : 'Вставить колонку до',
col_after_desc : 'Вставить котолку после',
delete_col_desc : 'Удалить колонку',
rowtype : 'Строка в части таблицы',
title : 'Вставить/Изменить таблицу',
width : 'Ширина',
height : 'Высота',
cols : 'Колонки',
rows : 'Строки',
cellspacing : 'Интервал ячеек',
cellpadding : 'Зазор ячеек',
border : 'Рамка',
align : 'Выравнивение',
align_default : 'По умолчанию',
align_left : 'Лево',
align_right : 'Право',
align_middle : 'Центр',
row_title : 'Свойства строки',
cell_title : 'Свойства ячейки',
cell_type : 'Тип ячейки',
row_desc : 'Свойства строки',
cell_desc : 'Свойства ячейки',
valign : 'Вертикальное выравнивание',
align_top : 'Верх',
align_bottom : 'Низ',
props_desc : 'Свойства таблицы',
bordercolor : 'Цвет рамки',
bgcolor : 'Цвет фона',
merge_cells_title : 'Объедигить ячейки',
split_cells_desc : 'Разделить ячейки',
merge_cells_desc : 'Объединить ячейки',
cut_row_desc : 'Вырезать строку',
copy_row_desc : 'Копировать строку',
paste_row_before_desc : 'Вставить строку до',
paste_row_after_desc : 'Вставить строку после',
id : 'Id',
style: 'Стиль',
langdir : 'Направление письма',
langcode : 'Код языка',
mime : 'Назначение типа MIME',
ltr : 'Слева направо',
rtl : 'Справа налево',
bgimage : 'Фоновый рисунок',
summary : 'Summary',
td : "Data",
th : "Header",
cell_cell : 'Обновить текущую ячейку',
cell_row : 'Обновить все ячейки с строке',
cell_all : 'Обновить все ячейки в таблице',
row_row : 'Обновить текущую строку',
row_odd : 'Обновить строки в таблице',
row_even : 'Обновить строки в таблице',
row_all : 'Обновить строки в таблице',
thead : 'Заголовок таблицы',
tbody : 'Тело таблицы',
tfoot : 'Футер таблицы',
del : 'Удалить таблицу',
scope : 'Область',
row : 'Строка',
col : 'Столбец',
rowgroup : 'Объединить строки',
colgroup : 'Объединить колонки',
missing_scope: 'Вы уверены, что хотите продолжить без указания этих параметров? Без этого части таблицы могут стать невидимыми или недоступными для юзеров.'
});
